[package]
name        = "crawlrs-frontier-redis"
description = "Redis-backed Frontier implementation for crawlrs."
version.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true
authors.workspace    = true

[dependencies]
crawlrs-core.workspace = true

async-trait.workspace = true
bb8.workspace         = true
bb8-redis.workspace   = true
postcard.workspace    = true
redis.workspace       = true
serde.workspace       = true
thiserror.workspace   = true
tokio.workspace       = true
tracing.workspace     = true
cuid2.workspace        = true

[dev-dependencies]
tokio                  = { workspace = true, features = ["rt-multi-thread", "macros", "time"] }
testcontainers.workspace         = true
testcontainers-modules.workspace = true

[lints]
workspace = true
